// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1e1bf05f-6e32-48a3-b3bb-e3c85b92aceb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IDpeh0IOy",
    "aws_user_pools_web_client_id": "2442fom21aleuj01d755c8sabe",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hu4rru4xo5g53op56quxqfs2oe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "stockphototestcab47f61653443049c0f7ad4a19ad15c-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
